version: '3.8'

services:
  db:
    image: postgres:14-alpine
    container_name: postgres-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qweasdzxc
      POSTGRES_DB: MovieBooking
    ports:
      - 5432:5432
    networks:
      - m-networks
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - db_data:/var/lib/postgresql/data
  
  redis:
    image: redis:alpine
    container_name: redis-container
    restart: always
    ports:
      - "6380:6379"
    networks:
      - m-networks
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - redis_data:/data

  app:
    build: .
    ports:
      - "6969:6969"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_SECRET=${GOOGLE_SECRET}
      - SECRET=cat
      - JWT_SECRET=${JWT_SECRET}
      - REDIS_URL=${REDIS_URL}
    networks:
      - m-networks
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: always

networks:
  m-networks:

volumes:
  db_data:
  redis_data:
